### PR TITLE
Fix `Base.show` so coefficients match variables and add simplest "realisitic" equation of state from Roquet et al. (2015)

### LINKED ISSUE #27: `Base.show` coefficients do not match variables
It looks like the coefficients do not match the variables in the `show` function for `SecondOrderSeawaterPolynomial`. Currently the `show` function is

```julia
function Base.show(io::IO, eos::SecondOrderSeawaterPolynomial)
    print(io, eos.R₁₀₀, " Sᴬ")
    print(io, signstr(eos.R₀₁₀), abs(eos.R₀₁₀), " Θ")
    print(io, signstr(eos.R₁₀₁), abs(eos.R₁₀₁), " Θ²")  
    print(io, signstr(eos.R₀₁₁), abs(eos.R₀₁₁), " Θ Z")
    print(io, signstr(eos.R₁₁₀), abs(eos.R₁₁₀), " Sᴬ²")
    print(io, signstr(eos.R₀₂₀), abs(eos.R₀₂₀), " Sᴬ Z")
    print(io, signstr(eos.R₂₀₀), abs(eos.R₂₀₀), " Sᴬ Θ")
end
```

but I think that the ` Θ²`,  `Sᴬ²`, `Sᴬ Z`, and `Sᴬ Θ` are not correct and should be

```julia
function Base.show(io::IO, eos::SecondOrderSeawaterPolynomial)
    print(io, eos.R₁₀₀, " Sᴬ")
    print(io, signstr(eos.R₀₁₀), abs(eos.R₀₁₀), " Θ")
    print(io, signstr(eos.R₀₂₀), abs(eos.R₀₂₀), " Θ²")
    print(io, signstr(eos.R₀₁₁), abs(eos.R₀₁₁), " Θ Z")
    print(io, signstr(eos.R₂₀₀), abs(eos.R₂₀₀), " Sᴬ²")
    print(io, signstr(eos.R₁₀₁), abs(eos.R₁₀₁), " Sᴬ Z")
    print(io, signstr(eos.R₁₁₀), abs(eos.R₁₁₀), " Sᴬ Θ")
end
```

This only occurs in this function (as far as I can see) and the rest of the package has coefficients and variables lining up correctly.

### PR DESCRIPTION
**Pull request by jbisits**
## Purpose 
Add the `coefficient_set` for the simplest yet "realisitic" equation of state from Roquet et al. (2015) and update `Base.show` for `::SecondOrderSeawaterPolynomial` so that coefficients match variables.
Closes #27 

## Content
The simplest yet "realistic" equation of state for seawater from Roquet et al. (2015) is equation (17). Following (17) the coefficients in the form $R_{\beta\chi\varphi}$ are given. This `coefficient_set` and tests are added to the `coefficient_set`s already in this package from Roquet et al. (2015), providing another equation of state that can be used.

This PR also updates `Base.show` so that the coefficients match the variables.

Apologies if this should have been two PR's, I only discovered #27 at the end of what I had initially set out to do which was add the simplest "realistic" eos from Roquet et al. (2015).

Review checklist

I have:
- followed the codebase contribution guide: https://clima.github.io/ClimateMachine.jl/latest/Contributing/
- followed the style guide: https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/
- followed the documentation policy: https://github.com/CliMA/policies/wiki/Documentation-Policy
- checked that this PR does not duplicate an open PR.

In the Content, I have included 
- relevant unit tests, and integration tests, 
- appropriate docstrings on all functions, structs, and modules, and included relevant documentation.

----
- [x] I have read and checked the items on the review checklist.

## References
[Roquet et al., "Defining a Simplified Yet “Realistic” Equation of State for Seawater", Journal of Physical Oceanography (2015)](https://doi.org/10.1175/JPO-D-15-0080.1)

### CODE REVIEW

File: src/SecondOrderSeawaterPolynomials.jl [hunk 1]
```diff
@@ -35,6 +35,7 @@ seawater_polynomial(Θ, Sᴬ, Z) = ⋯ + R₁₁₀ * Sᴬ * Θ + ⋯
 ```
 """
 @Base.kwdef struct SecondOrderSeawaterPolynomial{FT} <: AbstractSeawaterPolynomial
+    R₀₀₀ :: FT = 0
```
Comment (navidcy) [inline src/SecondOrderSeawaterPolynomials.jl]: Is this needed?

File: src/SecondOrderSeawaterPolynomials.jl [hunk 2]
```diff
@@ -136,7 +147,7 @@ RoquetEquationOfState(FT::DataType, coefficient_set=:SecondOrder; reference_dens
     BoussinesqEquationOfState(RoquetSeawaterPolynomial(FT, coefficient_set), reference_density)
 
 RoquetEquationOfState(coefficient_set=:SecondOrder; reference_density=1024.6) =
-    RoquetEquationOfState(Float64, coefficient_set, reference_density=1024.6)
+    RoquetEquationOfState(Float64, coefficient_set, reference_density)
```
Comment (navidcy) [inline src/SecondOrderSeawaterPolynomials.jl:150]: This is a breaking change, right?

File: src/SecondOrderSeawaterPolynomials.jl [hunk 3]
```diff
@@ -209,5 +220,27 @@ SecondOrderRoquetSeawaterPolynomial(FT=Float64) =
                                       R₂₀₀ = - 1.115e-4,
                                       R₁₀₁ = - 8.241e-6,
                                       R₁₁₀ = - 2.446e-3)
+"""
```
Comment (navidcy) [inline src/SecondOrderSeawaterPolynomials.jl:221]:
```suggestion

"""
```

empty line

File: src/SecondOrderSeawaterPolynomials.jl [hunk 4]
```diff
@@ -209,5 +220,27 @@ SecondOrderRoquetSeawaterPolynomial(FT=Float64) =
...
+    SimplestRealisticRoquetSeawaterPolynomial(FT=Float64)
```
Comment (navidcy) [inline src/SecondOrderSeawaterPolynomials.jl]:
```suggestion
    SimplestRealisticRoquetSeawaterPolynomial([FT=Float64])
```

File: src/SecondOrderSeawaterPolynomials.jl [hunk 5]
```diff
@@ -209,5 +220,27 @@ SecondOrderRoquetSeawaterPolynomial(FT=Float64) =
...
+temperature and salinity distribution.
+
+For more information see [`RoquetSeawaterPolynomial`](@ref).
+"""
+function SimplestRealisticRoquetSeawaterPolynomial(FT=Float64)
+
+    Cb = 0.011   # kgm⁻³K⁻²
+    Tₕ = 2.5e-5  # kgm⁻⁴K⁻ꜝ
+    b₀ = 0.77    # kgm⁻³(gkg⁻ꜝ)⁻ꜝ
+    Θ₀ = -4.5    # °C
```
Comment (navidcy) [inline src/SecondOrderSeawaterPolynomials.jl]:
```suggestion
    Cb = 0.011   # kg m⁻³ K⁻²
    Tₕ = 2.5e-5  # kg m⁻⁴ K⁻¹
    b₀ = 0.77    # kg m⁻³ (g kg⁻¹)⁻¹
    Θ₀ = -4.5    # °C
```

File: src/SecondOrderSeawaterPolynomials.jl (hunk 2 above)
Comment (navidcy) [reply src/SecondOrderSeawaterPolynomials.jl:150]: why changed the kwarg to arg?

Comment (navidcy) [inline src/SecondOrderSeawaterPolynomials.jl]:
```suggestion
    RoquetEquationOfState(Float64, coefficient_set; reference_density)
```

nice catch!
but to pass a keyword arg just with a variable name you need to add it after `;`.

this seems like a bug since regardless the value of `reference_density` the method would had always pass `1024.6`.

cc @glwagner

File: src/SecondOrderSeawaterPolynomials.jl (hunk 1 above)
Comment (glwagner) [reply src/SecondOrderSeawaterPolynomials.jl]: Our philosophy is to omit parameters that are not used. I don't think `R₀₀₀` is used so it should be omitted.

File: src/SecondOrderSeawaterPolynomials.jl (hunk 2 above)
Comment (glwagner) [reply src/SecondOrderSeawaterPolynomials.jl]: Definitely a good catch! I'm not aware of anyone who has ever used this. But we'll have to bump minor version and all that

Comment (navidcy) [reply src/SecondOrderSeawaterPolynomials.jl]: yeah

**Review by glwagner — CHANGES_REQUESTED** [review]
`R₀₀₀` does not appear in the thermal sensitivity or haline sensitivity:

image

Note that `R₀₀₀` is in fact equal to the reference density at the ocean surface. That's why we omit this coefficient.

I think we should remove `R₀₀₀` from this PR. However, we could add some additional explanation about the potential role of the "double zero" coefficients. With this equation of state, we cannot recover the in situ density at all depths because these coefficients are not tabulated by Roquet.

**Comment by jbisits** [comment]
> R₀₀₀ does not appear in the thermal sensitivity or haline sensitivity

Sorry, my mistake! Have now corrected `thermal_sensitivity` and `haline_sensitivity`.

**Comment by jbisits** [comment]
> Note that R₀₀₀ is in fact equal to the reference density at the ocean surface. That's why we omit this coefficient.
I think we should remove R₀₀₀ from this PR. However, we could add some additional explanation about the potential role of the "double zero" coefficients. With this equation of state, we cannot recover the in situ density at all depths because these coefficients are not tabulated by Roquet.

For reference (apologies about the resolution), here is the part of the paper that details the `density_anomaly` for the simplest yet "realisitic" eos in Roquet et al. (2015)
Roquet et al _2015_Defining a Simplified Yet “Realistic” Equation of State for Seawater (dragged)

This is why I added the `R₀₀₀` to `SecondOrderSeawaterPolynomial` because then we have 

$$
\rho = \rho_{r} + \rho'
$$

where $\rho'$ is equation (17) in the excerpt above which has the `R₀₀₀` coefficient.

I am happy to be guided by you on this and remove `R₀₀₀` but the inclusion of `R₀₀₀` is only for this `:SimplestRealisitcRoquetSeawaterPolynomial` as in all other cases  `R₀₀₀ = 0`.

File: src/SecondOrderSeawaterPolynomials.jl (hunk 1 above)
Comment (jbisits) [reply src/SecondOrderSeawaterPolynomials.jl]: `R₀₀₀` is used in `SimplestRealisiticRoquetSeawaterPolynomial`. See https://github.com/CliMA/SeawaterPolynomials.jl/pull/28#issuecomment-1467070184 below.

**Comment by glwagner** [comment]
> I am happy to be guided by you on this and remove R₀₀₀ but the inclusion of R₀₀₀ is only for this :SimplestRealisitcRoquetSeawaterPolynomial as in all other cases  R₀₀₀ = 0.

`R₀₀₀` has no effect on dynamics (or anything) right? What's the point of including it?

**Comment by jbisits** [comment]
> `R₀₀₀` has no effect on dynamics (or anything) right? What's the point of including it?

Yes that is right. The inclusion of `R₀₀₀` was just to be faithful to the Roquet et al. (2015) suggestion for the simplest "realistic" eos equation (17). Effectively `R₀₀₀` shifts the reference density by

```julia
(-0.011 * (-4.5)^2) / 2 # = -0.11137499999999999
```

so removing `R₀₀₀` is not likely to change things too much, so I will remove it now.

**Comment by glwagner** [comment]
I think that's for the best, because ideally users should not set or puzzle over this parameter. We can consider it absorbed into the user definition of reference density (which may also be used for thermodynamics calculations, etc).

File: src/SecondOrderSeawaterPolynomials.jl (hunk 1 above)
Comment (jbisits) [reply src/SecondOrderSeawaterPolynomials.jl]: Removed `R₀₀`₀

**Review by glwagner — APPROVED** [review]

**Comment by glwagner** [comment]
thanks!
